import { FormData } from "@/types/form-types";

export const characterPreviewSchema: FormData[] = [

    {
        name: "characterName",
        type: "text",
        label: "Character Name",
        disabled: true,
        cols: 12,
        row: 4,
        rows: "3",
    },
    {
        name: "visiable",
        type: "text",
        disabled: true,
        cols: 6,
        row: 4,
    },
    {
        name: "rating",
        type: "text",
        disabled: true,
        cols: 6,
        row: 4,
    },
    {
        name: "linkToLorebook",
        type: "text",
        disabled: true,
        label: "Link to Lorebook",
        placeholder: "Select Lorebook",
        cols: 6,
        row: 4,
        rows: "3",
    },
    {
        name: "linkToPersona",
        type: "text",
        disabled: true,
        label: "Link to Persona",
        placeholder: "Select Persona",
        cols: 6,
        row: 4,
        rows: "3",
    },
    {
        name: "tags",
        type: "text",
        label: "Choose Characters Tags",
        disabled: true,
        placeholder: "Single words describing your Character or Scenario.",
        cols: 12,
        row: 4,
        rows: "3",
    },
    {
        name: "description",
        type: "textarea",
        label: "Description",
        disabled: true,
        placeholder: "Describe your Character, Scenario, or Universe here...",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
    },
    {
        name: "scenario",
        type: "textarea",
        label: "Scenario",
        disabled: true,
        placeholder: "Describe the current circumstances of the chat.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
    },
    {
        name: "personalitySummary",
        type: "textarea",
        label: "Personality Summary",
        disabled: true,
        placeholder: "A short summary of your Character’s personality.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
    },
    {
        name: "firstMessage",
        type: "textarea",
        label: "First Message",
        disabled: true,
        placeholder: "Character's first message.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
    },
    {
        name: "alternateMessages",
        type: "text",
        label: "Alternate Messages",
        disabled: true,
        placeholder: "Add alternate first messages or greetings.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
    },
    {
        name: "exampleDialogue",
        type: "textarea",
        label: "Example Dialogue",
        disabled: true,
        placeholder: "Provide example conversations.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,

    },
    {
        name: "authorNotes",
        type: "textarea",
        label: "Author Notes",
        disabled: true,
        placeholder: "Private author notes about this character.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: false,
    },
    {
        name: "characterNotes",
        type: "textarea",
        label: "Character Notes",
        disabled: true,
        placeholder: "Any additional notes related to the character.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: false,
    },
    {
        name: "favourite",
        type: "checkbox",
        required: false,
        disabled: true,
        label: "Add To Favourites",
        cols: 12,
        row: 4,
        defaultValue: false
    },
];