import { FormData } from "@/types/form-types";

export const FeatureSchema: FormData[] = [
  {
    name: "title",
    type: "text",
    label: "Request Title",
    required: true,
    placeholder: "Enter a short, descriptive title",
    rules: {
      min: 4,
      max: 100,
    },
    cols: 12,
    row: 4,
  },
  {
    name: "priority",
    type: "select",
    label: "Priority Level",
    required: true,
    placeholder: "Select feature priority",
    rules: {
      options: [
        { label: "Low", value: "low" },
        { label: "Medium", value: "medium" },
        { label: "High", value: "high" },
        { label: "Critical", value: "critical" },
      ],
    },
    cols: 6,
    row: 4,
  },
  {
    name: "category",
    type: "select",
    label: "Feature Category",
    required: true,
    placeholder: "Select feature category",
    rules: {
      options: [
        { label: "UI/UX", value: "ui-ux" },
        { label: "Performance", value: "performance" },
        { label: "Integration", value: "integration" },
        { label: "Functionality", value: "functionality" },
        { label: "Other", value: "other" },
      ],
    },
    cols: 6,
    row: 4,
  },
  {
    name: "platform",
    type: "select",
    label: "Platform",
    required: true,
    placeholder: "Select target platform",
    rules: {
      options: [
        { label: "Web", value: "web" },
        { label: "Mobile", value: "mobile" },
        { label: "Desktop", value: "desktop" },
      ],
    },
    cols: 6,
    row: 4,
  },
  {
    name: "operating system",
    type: "select",
    label: "Operating System",
    required: true,
    placeholder: "Select target OS",
    rules: {
      options: [
        { label: "Web", value: "web" },
        { label: "Mobile", value: "mobile" },
        { label: "Desktop", value: "desktop" },
        { label: "API", value: "api" },
      ],
    },
    cols: 6,
    row: 4,
  },
  {
    label: "Feature Description or Description of Bug/Issue",
    type: "textarea",
    name: "Feature ",
    required: true,
    placeholder: "Please describe the feature you would like to add or the Bug you would like to report",
    cols: 12,
    row: 4,
    rows: "4",
  },
  {
    name: "additional_details",
    type: "textarea",
    label: "Additional Details (Optional)",
    required: false,
    placeholder: "Add any extra information, references, or examples",
    cols: 12,
    row: 4,
    rows: "3",
  },
    {
    name: "attachments",
    type: "multiple-file",
    label: "Upload Attachments (Optional)",
    required: false,
    cols: 12,
    row: 4,
  },
  {
    name: "requester_username",
    type: "text",
    label: "Requester UserName",
    required: true,
    placeholder: "John1234",
    cols: 6,
    row: 4,
  },
  {
    name: "requester_email",
    type: "text",
    label: "Requester Email",
    required: true,
    placeholder: "john@gmail.com",
    cols: 6,
    row: 4,
  },

];
